builders:
  nanoBuilder:
    import: "package:nano_generator/builder.dart"
    builder_factories: ["nanoBuilder"]
    build_extensions: {".dart": [".nano.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]